export const TOGGLE_DETAIL = "TOGGLE_DETAIL";
export const TOGGLE_FULL_MAP = "TOGGLE_FULL_MAP";
export const CHANGE_ROUTE = "CHANGE_ROUTE";
export const CHANGE_RESTAURANT = "CHANGE_RESTAURANT";
export const GET_RESTAURANTS = "GET_RESTAURANTS";